name: Backend CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Maven (Skip Tests)
      working-directory: ./backend
      run: mvn clean install -DskipTests

    - name: Deploy to Heroku
      working-directory: ./backend
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: |
        heroku deploy:jar target/*.jar --app <your-heroku-app-name>
