name: Backend CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Install Heroku CLI
      run: |
        curl https://cli-assets.heroku.com/install-ubuntu.sh | sh
        heroku --version  # Verify installation

    - name: Build with Maven (Skip Tests)
      working-directory: ./PoliticalApp
      run: mvn clean package -DskipTests  # Ensures .jar file is created

    - name: Deploy to Heroku
      working-directory: ./PoliticalApp
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: |
        heroku auth:token
        heroku deploy:war target/*.jar --app political-heroku
