name: Frontend CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      working-directory: ./political-app  # Ensure we are in the frontend folder
      run: npm install || echo "No package.json found, skipping npm install"

    - name: Install Vercel CLI
      run: npm install -g vercel

    - name: Deploy to Vercel
      working-directory: ./political-app  # Ensure deployment happens inside frontend folder
      env:
        VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      run: |
        npx vercel --prod --token $VERCEL_TOKEN --yes
