name: Frontend CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      working-directory: ./political-app  # Ensure npm install runs inside the correct folder
      run: npm install

    - name: Lint and Test
      working-directory: ./political-app  # Ensuring lint and tests run in the frontend folder
      run: |
        npm run lint || echo "Linting failed"
        npm test || echo "Tests failed"

    - name: Build and Deploy
      working-directory: ./political-app  # Ensuring deployment happens inside the frontend folder
      env:
        VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      run: |
        npx vercel --prod --token $VERCEL_TOKEN
